package Lexer;

public enum TokenType {
    LBRACKET,RBRACKET,
    INT,STRING,NUMBER,
    PLUS,MINUS,EQUAL,
    PRINT,IDENTIFIER,
    EQUAL_EQUAL,NOT_EQUAL,NOT,SMALLER,BIGGER,ESMALLER,EBIGGER,BANG,
    SEMICOLON,
    EOF
}
